name: ima-projet
channels:
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.3
  - asttokens=2.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - ca-certificates=2023.7.22
  - comm=0.1.4
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.2.0
  - ipykernel=6.25.2
  - ipython=8.12.0
  - jedi=0.19.0
  - jupyter_client=7.3.4
  - jupyter_core=5.3.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - openssl=3.1.3
  - packaging=23.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.16.1
  - python=3.8.18
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.10.1
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - wcwidth=0.2.7
  - wheel=0.41.2
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - contourpy=
    - cycler=
    - fonttools=
    - imageio=
    - importlib-resources=
    - joblib=
    - kiwisolver=
    - lazy-loader=
    - matplotlib=
    - networkx=
    - nibabel=
    - numpy=
    - opencv-python=
    - pandas=
    - pillow=
    - pyparsing=
    - pytz=
    - pywavelets=
    - scikit-image=
    - scikit-learn=
    - scipy=
    - threadpoolctl=
    - tifffile=
    - tzdata=
    - zipp=
